services:
  - type: web
    name: islamick-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: HEALTH_PORT
        value: 8080
